# Generated by Django 5.1.6 on 2025-05-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.PositiveBigIntegerField()),
                ('nom_site', models.CharField(blank=True, max_length=255, null=True)),
                ('bureau_dedie', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('nb_hommes_gestion', models.PositiveIntegerField()),
                ('nb_femmes_gestion', models.PositiveIntegerField()),
                ('comites_present', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('comites_eliges_par_population', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('comites_formes', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('reunions_organisees', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('comites_representatifs', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('comites_gestion', models.TextField(blank=True, null=True)),
                ('code_enqueteur', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GESTION DU SITE',
                'verbose_name_plural': 'GESTION DES SITES',
            },
        ),
        migrations.CreateModel(
            name='InformationGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.PositiveBigIntegerField()),
                ('nom_site', models.CharField(blank=True, max_length=255, null=True)),
                ('gestionnaireId', models.PositiveBigIntegerField()),
                ('nom_gestionnaire', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinateurId', models.PositiveBigIntegerField()),
                ('nom_coordinateur', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_menages', models.PositiveIntegerField()),
                ('nb_individus', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('code_enqueteur', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'INFORMATION GENERALE',
                'verbose_name_plural': 'INFORMATIONS GENERALES',
            },
        ),
        migrations.CreateModel(
            name='SanteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.PositiveBigIntegerField()),
                ('nom_site', models.CharField(blank=True, max_length=255, null=True)),
                ('prestataire_disponible', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('prestataire_dans_site', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('service_urgence', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('service_chirurgie', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('service_pediatrie', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('service_prenatal', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('enfants_non_vaccines', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('problemes_sante', models.TextField(blank=True, null=True)),
                ('obsacles_acces', models.TextField(blank=True, null=True)),
                ('code_enqueteur', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SANTE DU SITE',
                'verbose_name_plural': 'SANTE DES SITES',
            },
        ),
        migrations.CreateModel(
            name='WashSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.PositiveBigIntegerField()),
                ('nom_site', models.CharField(blank=True, max_length=255, null=True)),
                ('qte_eau_litres_par_personne', models.FloatField()),
                ('source_principale_eau', models.CharField(choices=[('Pompe à motricité humaine (PMH)', 'Pompe à motricité humaine (PMH)'), ('Puits à ciel ouvert', 'Puits à ciel ouvert'), ('Borne fontaine / Distribution', 'Borne fontaine / Distribution'), ('Water tracking', 'Water tracking'), ("Rivière / Cours d'eau", "Rivière / Cours d'eau"), ("Vendeur d'eau", "Vendeur d'eau"), ('Puits fermé', 'Puits fermé'), ('Eau en bouteille', 'Eau en bouteille'), ('Autre', 'Autre')], max_length=255)),
                ('signes_defecation_air_libre', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('jours_sans_eau_potable', models.PositiveIntegerField()),
                ('savon_disponible', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('inondations_dommages', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('methode_elimination_dechets', models.CharField(choices=[('Brûlage', 'Brûlage'), ('Fosse', 'Fosse'), ('Collecte organisée', 'Collecte organisée'), ('Autre', 'Autre')], max_length=255)),
                ('types_latrines_fonctionnelles', models.TextField(blank=True, null=True)),
                ('types_douches_fonctionnelles', models.TextField(blank=True, null=True)),
                ('douches_separees', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('latrines_vidangees', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('date_derniere_vidange', models.DateField(blank=True, null=True)),
                ('eclairage_latrines_douches', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('installation_adaptees_handicapes', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=255)),
                ('code_enqueteur', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WASH DU SITE',
                'verbose_name_plural': 'WASH DES SITES',
            },
        ),
    ]
