# Generated by Django 5.1.6 on 2025-05-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformationGenerale',
            new_name='InformationGeneraleProfilSite',
        ),
        migrations.RemoveField(
            model_name='gestionsite',
            name='nom_site',
        ),
        migrations.RemoveField(
            model_name='gestionsite',
            name='siteId',
        ),
        migrations.RemoveField(
            model_name='santesite',
            name='nom_site',
        ),
        migrations.RemoveField(
            model_name='santesite',
            name='siteId',
        ),
        migrations.RemoveField(
            model_name='washsite',
            name='nom_site',
        ),
        migrations.RemoveField(
            model_name='washsite',
            name='siteId',
        ),
        migrations.AddField(
            model_name='gestionsite',
            name='profil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_site', to='profil_site.informationgeneraleprofilsite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santesite',
            name='profil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sante_site', to='profil_site.informationgeneraleprofilsite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='washsite',
            name='profil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wash_site', to='profil_site.informationgeneraleprofilsite'),
            preserve_default=False,
        ),
    ]
