# Generated by Django 5.1.6 on 2025-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_site', '0003_remove_gestionsite_code_enqueteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washsite',
            name='methode_elimination_dechets',
            field=models.CharField(choices=[('Poubelle communale', 'Poubelle communale'), ('Fosse à ordures', 'Fosse à ordures'), ('Collecte privée', 'Collecte privée'), ('Jeter dans la rue / lieu ouvert', 'Jeter dans la rue / lieu ouvert'), ('Brûlage', 'Brûlage'), ('Fosse', 'Fosse'), ('Collecte organisée', 'Collecte organisée'), ('Autre', 'Autre')], max_length=255),
        ),
    ]
