# Generated by Django 5.1.6 on 2025-09-26 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_sitedeplace_type_propriete_fonciere'),
        ('profil_site', '0005_detailstypeabrisprofilsite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionProfilSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existance_restrictions_mouvement_interieur_exterieur', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=255)),
                ('restrictions_mouvement_rencontrees', models.TextField(blank=True, null=True)),
                ('tensions_entre_familles', models.CharField(max_length=255)),
                ('incidents_securite_produits', models.CharField(max_length=255)),
                ('acteurs_impliques_incidents_securite', models.TextField(blank=True, null=True)),
                ('nature_incidents_securite', models.TextField(blank=True, null=True)),
                ('personnes_sentiment_securite', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=255)),
                ('menances_plus_courantes', models.TextField(blank=True, null=True)),
                ('zones_insecurisees_femmes', models.TextField(blank=True, null=True)),
                ('zones_insecurisees_hommes', models.TextField(blank=True, null=True)),
                ('installantes_service_pvh_existantes', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=255)),
                ('types_services_soutien_psychosocial', models.TextField(blank=True, null=True)),
                ('nombres_familles_sans_documents_necessaires', models.PositiveBigIntegerField(default=0)),
                ('distance_avec_bureaux_etat', models.PositiveBigIntegerField(default=0)),
                ('accessibles_personnes_vulnerables', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.sitedeplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
