# Generated by Django 5.1.6 on 2025-09-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil_site', '0006_protectionprofilsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationprofilsite',
            old_name='nombre_enfants_en_age_scolaire_accedent_activites_educatives_informelles',
            new_name='nb_enfants_age_scolaire_acces_educatives_informelles',
        ),
    ]
