# Generated by Django 5.1.6 on 2025-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_site', '0007_rename_nombre_enfants_en_age_scolaire_accedent_activites_educatives_informelles_educationprofilsite_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitealimentaireprofilsite',
            old_name='repas_par_jour_familles',
            new_name='nombre_repas_par_jour_familles',
        ),
        migrations.AlterField(
            model_name='organisationinternefonctionnementprofilsite',
            name='nb_femmes_gestion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organisationinternefonctionnementprofilsite',
            name='nb_hommes_gestion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
