# Generated by Django 5.1.6 on 2025-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_site', '0008_rename_repas_par_jour_familles_securitealimentaireprofilsite_nombre_repas_par_jour_familles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_abris_ame',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_assainissement',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_cohension_sociale',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_communication',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_dechets',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_education',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_moyens_subsistance',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_nutrition',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_protection',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_protection_enfants',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_sante_eau',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_sante_mental_psychosociaux',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_sante_secondaires',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_santes_primaires',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_securite_alimentaire',
        ),
        migrations.RemoveField(
            model_name='cartographieserviceacteurprofilsite',
            name='existance_partenaires_vbg',
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_abris_ame',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_assainissement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_cohension_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_communication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_dechets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_moyens_subsistance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_nutrition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_protection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_protection_enfants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_sante_eau',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_sante_mental_psychosociaux',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_sante_secondaires',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_santes_primaires',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_securite_alimentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartographieserviceacteurprofilsite',
            name='noms_partenaires_vbg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
