# Generated by Django 5.1.6 on 2025-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_coordonneessite_url_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonneessite',
            name='coordinateur_site',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coordonneessite',
            name='gestionnaire_site',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coordonneessite',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coordonneessite',
            name='site_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='coordonneessite',
            name='territoire',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coordonneessite',
            name='type_site',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coordonneessite',
            name='zone_sante',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='activite',
            field=models.PositiveBigIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='coordinateur_site',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='date_enregistrement',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='enqueteur',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='gestionnaire_site',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='organisation',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='site',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='statutmouvement',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='territoire',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='type_site',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='typemouvement',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mouvementdeplace',
            name='zone_sante',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
