# Generated by Django 5.1.6 on 2025-07-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDeplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=300, null=True)),
                ('code_province', models.CharField(blank=True, max_length=300, null=True)),
                ('territoire', models.CharField(blank=True, max_length=300, null=True)),
                ('code_territoire', models.CharField(blank=True, max_length=300, null=True)),
                ('zone_sante', models.CharField(blank=True, max_length=300, null=True)),
                ('code_zone_sante', models.CharField(blank=True, max_length=300, null=True)),
                ('type_site', models.CharField(blank=True, max_length=300, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('code_site', models.CharField(blank=True, max_length=300, null=True)),
                ('nom_site', models.CharField(max_length=300)),
                ('sous_mecanisme', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MouvementDeplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menages', models.PositiveBigIntegerField(default=0)),
                ('individus', models.PositiveBigIntegerField(default=0)),
                ('type_mouvement', models.CharField(default='entree_initiale', max_length=300)),
                ('pvh', models.PositiveBigIntegerField(default=0)),
                ('date_mise_a_jour', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.sitedeplace')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalMouvementDeplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menages', models.PositiveBigIntegerField(default=0)),
                ('individus', models.PositiveBigIntegerField(default=0)),
                ('pvh', models.PositiveBigIntegerField(default=0)),
                ('date_mise_a_jour', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.sitedeplace')),
            ],
        ),
    ]
