# Generated by Django 5.1.6 on 2025-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_0_4_f',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_0_4_h',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_12_17_f',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_12_17_h',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_18_24_f',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_18_24_h',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_25_59_f',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_25_59_h',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_5_11_f',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_5_11_h',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_60_f',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mouvementdeplace',
            name='individus_60_h',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
