# Generated by Django 5.1.6 on 2025-08-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_mouvementdeplace_individus_0_4_f_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MouvementDeplaceSiteUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('Mai 2023', 'Mai2023'), ('Juin 2023', 'Juin2023'), ('Juillet 2023', 'Juillet2023'), ('Aout 2023', 'Aout2023'), ('Septembre 2023', 'Sept2023'), ('Octobre 2023', 'Oct2023'), ('Novembre 2023', 'Nov2023'), ('Decembre 2023', 'Dec2023'), ('Janvier 2024', 'Janv2024'), ('Fevrier 2024', 'Fev2024'), ('Mars 2024', 'Mars2024'), ('Avril 2024', 'Avril2024'), ('Mai 2024', 'Mai2024'), ('Juin 2024', 'Juin2024'), ('Juillet 2024', 'Juillet2024'), ('Aout 2024', 'Aout2024'), ('Septemembre 2024', 'Sept2024'), ('Octobre 2024', 'Oct2024'), ('Novembre 2024', 'Nov2024'), ('Janvier 2025', 'Janv2025'), ('Fevrier 2025', 'Fev2025'), ('Mars 2025', 'Mars2025')], max_length=200)),
                ('menages', models.PositiveBigIntegerField(default=0)),
                ('individus', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.siteunique')),
            ],
        ),
    ]
