# Generated by Django 5.1.6 on 2025-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_alter_mouvementdeplacesiteunique_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedeplace',
            name='coordinateur',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitedeplace',
            name='gestionnaire',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
