# Generated by Django 5.1.6 on 2025-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_sitedeplace_coordinateur_sitedeplace_gestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedeplace',
            name='code_province',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='code_site',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='code_territoire',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='code_zone_sante',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='coordinateur',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='gestionnaire',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='nom_site',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='sous_mecanisme',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='territoire',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='type_site',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sitedeplace',
            name='zone_sante',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
