# Generated by Django 5.1.6 on 2025-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_alter_sitedeplace_code_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedeplace',
            name='type_propriete_fonciere',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
