DATA = [
    {
        "code_site": "CD6101ZS01S014SPHM",
        "enqueteur": "Essaie",
        "organisation": "AIDES",
        "concerne_nouveau_site": "Non",
        "nombre_menages": 667,
        "nombre_individus": 1627,
        "individus_0_4_f": 0,
        "individus_5_11_f": 0,
        "individus_12_17_f": 0,
        "individus_18_24_f": 0,
        "individus_25_59_f": 0,
        "individus_60_f": 0,
        "individus_0_4_h": 0,
        "individus_5_11_h": 0,
        "individus_12_17_h": 0,
        "individus_18_24_h": 0,
        "individus_25_59_h": 0,
        "individus_60_h": 0,
        "statut_site": "Fonctionnel",
        "gestion_administration": {
            "gestionnaire": "ACTED",
            "contact_gestionnaire": "",
            "administrateur": "",
            "contact_administrateur": "",
            "coordinateur": "UNHCR",
            "contact_coordinateur": "",
        },
        "organisation_fonctionnement": {
            "bureau_dedie": "Oui",
            "nb_hommes_gestion": 52,
            "nb_femmes_gestion": 25,
            "comites_present": "Oui",
            "comites_gestion": "Comité de gestion du SITE; Comité des femmes; Comité des jeunes",
            "comites_eliges_par_population": "Non",
            "comites_fonctionne": "Tous les comités fonctionnent",
            "nb_comites_fonctionnels": 3,
            "comites_formes": "Partiellement",
            "reunions_organisees": "Oui",
            "comites_representatifs": "Oui",
            "nom_equipe_mobile_gestion": "",
            "methodes_annonce_distribution": "Comités de site; Autres (veuillez préciser)",
            "centre_communautaire": "Non",
            "mecanisme_gestion_plainte": "Non",
            "rencontres_coordination": "Oui",
            "rencontres_planification": "Hebdommadaire",
        },
        "vulnerabilites": {
            "nouvelle_arrivees_mois": 0,
            "retourneees_mois": 0,
            "raisons_retour": "",
            "menages_diriges_femmes": 0,
            "menages_diriges_enfants": 0,
            "enfants_non_accompagnes": 0,
            "personnes_handicaps_physiques": 0,
            "personnes_handicaps_mentaux": 0,
            "personnes_maladies_chroniques": 0,
            "personnes_agees_sans_membre": 0,
        },
        "abris_ame": {
            "details_types_abris": [
                {
                    "type_abris": "Tente en bache",
                    "nombre_installes": 25,
                    "nombre_occupees": 58,
                    "nombre_occupees_maintenance": 25,
                    "nombre_occupees_remplacement": 255,
                }
            ],
            "capacite_accueil_max": 0,
            "familles_attente_parcelle_abris": 0,
            "fermeture_site_prevue": "Non",
            "types_abris_present": "Tente en bache; Tente en materiaux",
            "nombre_abris_occupes_maintenance": 52,
            "nombre_abris_occupes_remplacement": 55,
            "besoins_en_ames": "Articles de literie (draps de lit, oreillers); Matelas/tapis de couchage",
            "besoins_ames_saison_seche": "Stockage d'eau supplémentaire; Vêtements adaptés à la chaleur",
            "strategies_adaptation_ames": "Pas besoin d'utiliser une stratégie d'adaptation car il n'y a pas de problème d'abri ou de AME",
            "etat_generale_parcelle_communautaire": "Besoin d'un entretien lourd",
            "etat_generale_routes": "Nécessite une mise à niveau : (ajout d'une couche de gravier écrasé, double couche de dressage, coulage de béton, asphaltage, etc.)",
            "etat_generale_canaux_evacuations_eaux_pluviales": "Nécessite un entretien lourd : (utilisation de machines pour dégager/nettoyer, refonte du béton pour les parties endommagées, etc.)",
            "inodations_derniers_saison": "Non",
            "nombre_incendies_ce_mois": 0,
            "existance_mesures_prevention_incendies": "Non",
            "eclairage_existant": "Non",
            "source_principale_energetique": "",
        },
        "wash": {
            "nombre_litres_personne_jour": 0,
            "principale_source_eau_potable": "Pompe à motricité humaine (PMH); Puit à ciel ouvert",
            "source_principale_eau_potable_acceptable": "Oui",
            "nombre_moyen_jours_sans_eau_potable": 0,
            "signes_defecation_plein_air": "Oui",
            "savon_generalement_disponible": "Oui",
            "inondations_dommages": "Non",
            "methode_elimination_dechets": "Poubelle communale",
            "types_latrines_fonctionnelles": "Latrines publiques semi-durable",
            "nombre_latrines_fonctionnelles": 25,
            "types_douches_fonctionnelles": "Douches publiques (semi-durable)",
            "nombre_douches_fonctionnelles": 25,
            "douches_separees": "Non",
            "latrines_vidangees": "Non",
            "date_derniere_vidange": None,
            "eclairage_latrines_douches": "Non",
            "installation_adaptees_handicapes": "Non",
        },
        "sante": {
            "problemes_sante": "Nombreux cas de diarrhée; Maladies de la peau (gale, éruptions contagieuses, etc.)",
            "prestataire_sante_disponible": "Oui",
            "prestataire_sante_dans_site": "Non",
            "distance_prestataire": 8,
            "service_urgence": "Non",
            "service_chirurgie": "Non",
            "service_pediatrie": "Oui",
            "service_prenatal": "Non",
            "fournit_ambulance": "Non",
            "problemes_familles_acceder_soins": "Le coût des soins de santé était trop élevé; Pas de professionnels de santé qualifiés",
            "enfants_non_vaccines": 170,
        },
        "securite_alimentaire": {
            "nombre_repas_par_jour_familles": 1,
            "difficultes_rencontrees_acces_nourriture": "Pas d'installations de cuisson",
            "existance_magasins_stockages_vivres": "Non",
            "regularite_aide_alimentaire_derniers_mois": "Tous les jours",
        },
        "protection": {
            "existance_restrictions_mouvement_interieur_exterieur": "Non",
            "restrictions_mouvement_rencontrees": "",
            "tensions_entre_familles": "Oui",
            "incidents_securite_produits": "Non",
            "acteurs_impliques_incidents_securite": "",
            "nature_incidents_securite": "",
            "personnes_sentiment_securite": "Oui",
            "menances_plus_courantes": "",
            "zones_insecurisees_femmes": "",
            "zones_insecurisees_hommes": "",
            "installantes_service_pvh_existantes": "Oui",
            "types_services_soutien_psychosocial": "",
            "nombres_familles_sans_documents_necessaires": 76,
            "distance_avec_bureaux_etat": 76,
            "accessibles_personnes_vulnerables": "Oui",
        },
        "education": {
            "existance_ecoles_primaire_fonctionnelles": "Non",
            "distance_ecole_primaire_avec_site": 34,
            "existance_ecoles_secondaire_fonctionnelles": "Oui",
            "distance_ecole_secondaire_avec_site": 10,
            "nombre_enfants_en_age_scolaire_sont_scolarises": 258,
            "principales_obstacles_scolarisation": "Pas assez d'écoles ou de salles de classe; Pas assez d'enseignants",
            "activites_educatives_informelle_existantes": "Non",
            "nb_enfants_age_scolaire_acces_educatives_informelles": 2,
        },
        "moyens_subsistance": {
            "marche_existant_interieur_site": "Non",
            "distance_marche_avec_site": 10,
            "articles_necessaires_inexistantes_marche": "Produits alimentaires de base",
            "principaux_moyers_subsistance": "Agriculture commerciale; Agriculture de subsistance",
            "nombre_familles_gagnant_revenu_derniers_jours": 5,
            "nombre_jeunes_avec_travail": 5,
            "existance_enclos_betails": "Non",
            "premier_besoin_prioritaire": "Abris/Assistance en maintenance abri",
            "deuxieme_besoin_prioritaire": "Amenagement du site",
            "troisieme_besoin_prioritaire": "Eau potable",
        },
        "cartographie_acteurs_services": {
            "service_education": "Adequat",
            "distribution_vivres": "Inadequat",
            "service_sante": "Inadequat",
            "service_sante_mental_psychosocial": "Inadequat",
            "service_moyen_existance": "Inadequat",
            "distribution_cash": "Inexistant",
            "distribution_nfi_ame": "Inexistant",
            "service_protection": "Inexistant",
            "service_maintenace_abris": "Inexistant",
            "service_wash": "Inexistant",
            "service_elimination_dechets": "Inexistant",
            "noms_partenaires_protection": "Association Vision Plus (AVP); Caritas RDC",
            "noms_partenaires_vbg": "",
            "noms_partenaires_protection_enfants": "",
            "noms_partenaires_education": "",
            "noms_partenaires_abris_ame": "",
            "noms_partenaires_sante_eau": "",
            "noms_partenaires_assainissement": "",
            "noms_partenaires_dechets": "",
            "noms_partenaires_santes_primaires": "",
            "noms_partenaires_sante_secondaires": "",
            "noms_partenaires_sante_mental_psychosociaux": "",
            "noms_partenaires_nutrition": "",
            "noms_partenaires_securite_alimentaire": "",
            "noms_partenaires_cohension_sociale": "",
            "noms_partenaires_moyens_subsistance": "",
            "noms_partenaires_communication": "",
        },
    },
    {
        "code_site": "CD6101ZS01S206SSSM",
        "enqueteur": "AIDES",
        "organisation": "AIDES",
        "concerne_nouveau_site": "Non",
        "nombre_menages": 13520,
        "nombre_individus": 57748,
        "individus_0_4_f": None,
        "individus_5_11_f": None,
        "individus_12_17_f": None,
        "individus_18_24_f": None,
        "individus_25_59_f": None,
        "individus_60_f": None,
        "individus_0_4_h": None,
        "individus_5_11_h": None,
        "individus_12_17_h": None,
        "individus_18_24_h": None,
        "individus_25_59_h": None,
        "individus_60_h": None,
        "statut_site": "Fonctionnel",
        "gestion_administration": {
            "gestionnaire": "AIDES",
            "contact_gestionnaire": "97100840",
            "administrateur": "CNR",
            "contact_administrateur": "994179394",
            "coordinateur": "UNHCR",
            "contact_coordinateur": "",
        },
        "organisation_fonctionnement": {
            "bureau_dedie": "Oui",
            "nb_hommes_gestion": 5,
            "nb_femmes_gestion": 1,
            "comites_present": "Oui",
            "comites_gestion": "Comité éducation; Comité santé; Autre comité; Comité de distribution; Comité des femmes; Comité de gestion du SITE; Comité de maintenance; Comité WASH; Comité des jeunes",
            "comites_eliges_par_population": "Non",
            "comites_fonctionne": "Tous les comités fonctionnent",
            "nb_comites_fonctionnels": 9,
            "comites_formes": "Partiellement",
            "reunions_organisees": "Oui",
            "comites_representatifs": "Oui",
            "nom_equipe_mobile_gestion": "",
            "methodes_annonce_distribution": "Comités de site; Autres (veuillez préciser); Équipe de gestion du site",
            "centre_communautaire": "Oui",
            "mecanisme_gestion_plainte": "Oui",
            "rencontres_coordination": "Non",
            "rencontres_planification": "Hebdommadaire",
        },
        "vulnerabilites": {
            "nouvelle_arrivees_mois": 0,
            "retourneees_mois": 0,
            "raisons_retour": "",
            "menages_diriges_femmes": 0,
            "menages_diriges_enfants": 0,
            "enfants_non_accompagnes": 0,
            "personnes_handicaps_physiques": 0,
            "personnes_handicaps_mentaux": 0,
            "personnes_maladies_chroniques": 0,
            "personnes_agees_sans_membre": 0,
        },
        "abris_ame": {
            "details_types_abris": [
                {
                    "type_abris": "Tente en bache",
                    "nombre_installes": 10500,
                    "nombre_occupees": 10500,
                    "nombre_occupees_maintenance": 6000,
                    "nombre_occupees_remplacement": 4000,
                }
            ],
            "capacite_accueil_max": 0,
            "familles_attente_parcelle_abris": 0,
            "fermeture_site_prevue": "Non",
            "types_abris_present": "Tente en bache",
            "nombre_abris_occupes_maintenance": 71400,
            "nombre_abris_occupes_remplacement": 14019,
            "besoins_en_ames": "Vêtements; Bâche; Ustensiles de cuisine; Matelas/tapis de couchage",
            "besoins_ames_saison_seche": "Stockage d'eau supplémentaire; Vêtements adaptés à la chaleur",
            "strategies_adaptation_ames": "Autres",
            "etat_generale_parcelle_communautaire": "Bon",
            "etat_generale_routes": "Nécessite une mise à niveau : (ajout d'une couche de gravier écrasé, double couche de dressage, coulage de béton, asphaltage, etc.)",
            "etat_generale_canaux_evacuations_eaux_pluviales": "Pas de caniveaux",
            "inodations_derniers_saison": "Non",
            "nombre_incendies_ce_mois": 0,
            "existance_mesures_prevention_incendies": "Non",
            "eclairage_existant": "Non",
            "source_principale_energetique": "Poteaux solaires",
        },
        "wash": {
            "nombre_litres_personne_jour": 0,
            "principale_source_eau_potable": "Distribution d'eau/Borne fontaine; Water tracking",
            "source_principale_eau_potable_acceptable": "Oui",
            "nombre_moyen_jours_sans_eau_potable": 0,
            "signes_defecation_plein_air": "Oui",
            "savon_generalement_disponible": "Oui",
            "inondations_dommages": "Non",
            "methode_elimination_dechets": "Poubelle communale",
            "types_latrines_fonctionnelles": "Latrines publiques semi-durable",
            "nombre_latrines_fonctionnelles": 600,
            "types_douches_fonctionnelles": "Douches publiques (semi-durable)",
            "nombre_douches_fonctionnelles": 200,
            "douches_separees": "Oui",
            "latrines_vidangees": "Oui",
            "date_derniere_vidange": "2024-11-05",
            "eclairage_latrines_douches": "Oui",
            "installation_adaptees_handicapes": "Oui",
        },
        "sante": {
            "problemes_sante": "Nombreux cas de diarrhée; Nombreux cas de paludisme; MPOX",
            "prestataire_sante_disponible": "Oui",
            "prestataire_sante_dans_site": "Non",
            "distance_prestataire": 200,
            "service_urgence": "Non",
            "service_chirurgie": "Non",
            "service_pediatrie": "Oui",
            "service_prenatal": "Non",
            "fournit_ambulance": "Non",
            "problemes_familles_acceder_soins": "Fonds insuffisants pour acheter le traitement/les médicaments",
            "enfants_non_vaccines": 170,
        },
        "securite_alimentaire": {
            "nombre_repas_par_jour_familles": 1,
            "difficultes_rencontrees_acces_nourriture": "Accès limité à la nourriture en raison de contraintes de sécurité; Accès limité à la nourriture en raison de ressources économiques limitées",
            "existance_magasins_stockages_vivres": "Non",
            "regularite_aide_alimentaire_derniers_mois": "Entre 2 et 3 mois",
        },
        "protection": {
            "existance_restrictions_mouvement_interieur_exterieur": "Non",
            "restrictions_mouvement_rencontrees": "",
            "tensions_entre_familles": "Oui",
            "incidents_securite_produits": "Oui",
            "acteurs_impliques_incidents_securite": "FRDC (Militaire, gendamerie); Groupes armés",
            "nature_incidents_securite": "Tuerie",
            "personnes_sentiment_securite": "Oui",
            "menances_plus_courantes": "Crainte des acteurs armés de la sécurité (recrutement, détention, violence, menaces ou harcèlement)",
            "zones_insecurisees_femmes": "En dehors du site (champ)",
            "zones_insecurisees_hommes": "Préfère ne pas dire",
            "installantes_service_pvh_existantes": "Oui",
            "types_services_soutien_psychosocial": "Premiers secours psychologiques",
            "nombres_familles_sans_documents_necessaires": 76,
            "distance_avec_bureaux_etat": 76,
            "accessibles_personnes_vulnerables": "Oui",
        },
        "education": {
            "existance_ecoles_primaire_fonctionnelles": "Non",
            "distance_ecole_primaire_avec_site": 600,
            "existance_ecoles_secondaire_fonctionnelles": "Oui",
            "distance_ecole_secondaire_avec_site": 7,
            "nombre_enfants_en_age_scolaire_sont_scolarises": 1000,
            "principales_obstacles_scolarisation": "Pas assez d'écoles ou de salles de classe; Contraintes physiques/logistiques; Ressources économiques limitées (par exemple, pour payer les frais de scolarité, l'uniforme, le transport, les livres, etc.)",
            "activites_educatives_informelle_existantes": "Non",
            "nb_enfants_age_scolaire_acces_educatives_informelles": 1000,
        },
        "moyens_subsistance": {
            "marche_existant_interieur_site": "Non",
            "distance_marche_avec_site": 15,
            "articles_necessaires_inexistantes_marche": "Articles d'hygiène; Articles ménagers de base (par exemple, matelas, couvertures, ustensiles de cuisine)",
            "principaux_moyers_subsistance": "L'agriculture des petits exploitants; Travail occasionnel non qualifié",
            "nombre_familles_gagnant_revenu_derniers_jours": 0,
            "nombre_jeunes_avec_travail": 200,
            "existance_enclos_betails": "Non",
            "premier_besoin_prioritaire": "Assistance en cash",
            "deuxieme_besoin_prioritaire": "Eau potable",
            "troisieme_besoin_prioritaire": "Service de protection",
        },
        "cartographie_acteurs_services": {
            "service_education": "Inadequat",
            "distribution_vivres": "Inadequat",
            "service_sante": "Inadequat",
            "service_sante_mental_psychosocial": "Inadequat",
            "service_moyen_existance": "Inadequat",
            "distribution_cash": "Adequat",
            "distribution_nfi_ame": "Adequat",
            "service_protection": "Adequat",
            "service_maintenace_abris": "Adequat",
            "service_wash": "Adequat",
            "service_elimination_dechets": "Adequat",
            "noms_partenaires_protection": "WeWorld-GVC (WW-GVC); INTERSOS",
            "noms_partenaires_vbg": "WeWorld-GVC (WW-GVC)",
            "noms_partenaires_protection_enfants": "",
            "noms_partenaires_education": "",
            "noms_partenaires_abris_ame": "",
            "noms_partenaires_sante_eau": "",
            "noms_partenaires_assainissement": "",
            "noms_partenaires_dechets": "",
            "noms_partenaires_santes_primaires": "",
            "noms_partenaires_sante_secondaires": "",
            "noms_partenaires_sante_mental_psychosociaux": "",
            "noms_partenaires_nutrition": "",
            "noms_partenaires_securite_alimentaire": "",
            "noms_partenaires_cohension_sociale": "",
            "noms_partenaires_moyens_subsistance": "",
            "noms_partenaires_communication": "",
        },
    },
    {
        "code_site": "CD6205ZS04S073SSHM",
        "enqueteur": "TIMOTHE FATAKI",
        "organisation": "CIAUD",
        "concerne_nouveau_site": "Non",
        "nombre_menages": 391,
        "nombre_individus": 1483,
        "individus_0_4_f": None,
        "individus_5_11_f": None,
        "individus_12_17_f": None,
        "individus_18_24_f": None,
        "individus_25_59_f": None,
        "individus_60_f": None,
        "individus_0_4_h": None,
        "individus_5_11_h": None,
        "individus_12_17_h": None,
        "individus_18_24_h": None,
        "individus_25_59_h": None,
        "individus_60_h": None,
        "statut_site": "Fonctionnel",
        "gestion_administration": {
            "gestionnaire": "CIAUD",
            "contact_gestionnaire": "666666666",
            "administrateur": "DIVAH",
            "contact_administrateur": "856709876",
            "coordinateur": "UNHCR",
            "contact_coordinateur": "",
        },
        "organisation_fonctionnement": {
            "bureau_dedie": "Non",
            "nb_hommes_gestion": 6,
            "nb_femmes_gestion": 4,
            "comites_present": "Oui",
            "comites_gestion": "Comité de gestion du SITE; Comité santé; Comité éducation; Comité WASH; Comité de maintenance; Comité de distribution; Comité des jeunes; Comité des femmes",
            "comites_eliges_par_population": "Oui",
            "comites_fonctionne": "Tous les comités fonctionnent",
            "nb_comites_fonctionnels": 8,
            "comites_formes": "Oui",
            "reunions_organisees": "Oui",
            "comites_representatifs": "Oui",
            "nom_equipe_mobile_gestion": "",
            "methodes_annonce_distribution": "Équipe de gestion du site; Bouche à oreille",
            "centre_communautaire": "Non",
            "mecanisme_gestion_plainte": "Non",
            "rencontres_coordination": "Non",
            "rencontres_planification": "Hebdommadaire",
        },
        "vulnerabilites": {
            "nouvelle_arrivees_mois": 0,
            "retourneees_mois": 0,
            "raisons_retour": "",
            "menages_diriges_femmes": 0,
            "menages_diriges_enfants": 0,
            "enfants_non_accompagnes": 0,
            "personnes_handicaps_physiques": 0,
            "personnes_handicaps_mentaux": 0,
            "personnes_maladies_chroniques": 0,
            "personnes_agees_sans_membre": 0,
        },
        "abris_ame": {
            "details_types_abris": [
                {
                    "type_abris": "Tente en bache",
                    "nombre_installes": 86,
                    "nombre_occupees": 72,
                    "nombre_occupees_maintenance": 45,
                    "nombre_occupees_remplacement": 20,
                }
            ],
            "capacite_accueil_max": 0,
            "familles_attente_parcelle_abris": 0,
            "fermeture_site_prevue": "Non",
            "types_abris_present": "Tente en bache",
            "nombre_abris_occupes_maintenance": 2,
            "nombre_abris_occupes_remplacement": 2,
            "besoins_en_ames": "Articles de literie (draps de lit, oreillers); Couvertures; Kit d'hygiène intime; Bassine de lavage",
            "besoins_ames_saison_seche": "Vêtements adaptés à la chaleur; Stockage d'eau supplémentaire",
            "strategies_adaptation_ames": "Vente d'actifs/de biens du ménage (bijoux, téléphone, etc.); Vente de certains articles d'assistance reçus; Envoyer les enfants au travail",
            "etat_generale_parcelle_communautaire": "Besoin d'un entretien léger",
            "etat_generale_routes": "Besoin d'un entretien léger",
            "etat_generale_canaux_evacuations_eaux_pluviales": "Nécessite un entretien lourd : (utilisation de machines pour dégager/nettoyer, refonte du béton pour les parties endommagées, etc.)",
            "inodations_derniers_saison": "Non",
            "nombre_incendies_ce_mois": 0,
            "existance_mesures_prevention_incendies": "Non",
            "eclairage_existant": "Non",
            "source_principale_energetique": "",
        },
        "wash": {
            "nombre_litres_personne_jour": 0,
            "principale_source_eau_potable": "Puit à ciel ouvert",
            "source_principale_eau_potable_acceptable": "Oui",
            "nombre_moyen_jours_sans_eau_potable": 0,
            "signes_defecation_plein_air": "Oui",
            "savon_generalement_disponible": "Oui",
            "inondations_dommages": "Non",
            "methode_elimination_dechets": "Fosse à ordures",
            "types_latrines_fonctionnelles": "Latrines publiques semi-durable; Latrines publiques d'urgence",
            "nombre_latrines_fonctionnelles": 6,
            "types_douches_fonctionnelles": "Douches publiques (semi-durable)",
            "nombre_douches_fonctionnelles": 13,
            "douches_separees": "Oui",
            "latrines_vidangees": "Oui",
            "date_derniere_vidange": "2024-12-07",
            "eclairage_latrines_douches": "Non",
            "installation_adaptees_handicapes": "Non",
        },
        "sante": {
            "problemes_sante": "Nombreux cas de diarrhée; Maladies de la peau (gale, éruptions contagieuses, etc.)",
            "prestataire_sante_disponible": "Oui",
            "prestataire_sante_dans_site": "Non",
            "distance_prestataire": 18,
            "service_urgence": "Non",
            "service_chirurgie": "Non",
            "service_pediatrie": "Oui",
            "service_prenatal": "Non",
            "fournit_ambulance": "Non",
            "problemes_familles_acceder_soins": "Aucun",
            "enfants_non_vaccines": 170,
        },
        "securite_alimentaire": {
            "nombre_repas_par_jour_familles": 1,
            "difficultes_rencontrees_acces_nourriture": "Aucune",
            "existance_magasins_stockages_vivres": "Non",
            "regularite_aide_alimentaire_derniers_mois": "Entre 2 et 3 mois",
        },
        "protection": {
            "existance_restrictions_mouvement_interieur_exterieur": "Non",
            "restrictions_mouvement_rencontrees": "",
            "tensions_entre_familles": "Oui",
            "incidents_securite_produits": "Non",
            "acteurs_impliques_incidents_securite": "",
            "nature_incidents_securite": "",
            "personnes_sentiment_securite": "Oui",
            "menances_plus_courantes": "Crainte des groupes communautaires/tribaux (violence, menaces, harcèlement liés à un conflit en cours)",
            "zones_insecurisees_femmes": "Centre de distribution",
            "zones_insecurisees_hommes": "Préfère ne pas dire",
            "installantes_service_pvh_existantes": "Oui",
            "types_services_soutien_psychosocial": "",
            "nombres_familles_sans_documents_necessaires": 76,
            "distance_avec_bureaux_etat": 76,
            "accessibles_personnes_vulnerables": "Oui",
        },
        "education": {
            "existance_ecoles_primaire_fonctionnelles": "Non",
            "distance_ecole_primaire_avec_site": 6,
            "existance_ecoles_secondaire_fonctionnelles": "Non",
            "distance_ecole_secondaire_avec_site": 7,
            "nombre_enfants_en_age_scolaire_sont_scolarises": 120,
            "principales_obstacles_scolarisation": "Pas assez d'écoles ou de salles de classe; Pas assez de matériel pédagogique; Longue distance à parcourir pour se rendre à l'école",
            "activites_educatives_informelle_existantes": "Non",
            "nb_enfants_age_scolaire_acces_educatives_informelles": 0,
        },
        "moyens_subsistance": {
            "marche_existant_interieur_site": "Non",
            "distance_marche_avec_site": 15,
            "articles_necessaires_inexistantes_marche": "Articles d'hygiène; Articles ménagers de base (par exemple, matelas, couvertures, ustensiles de cuisine)",
            "principaux_moyers_subsistance": "Agriculture commerciale; Travail occasionnel non qualifié; Sécurité sociale",
            "nombre_familles_gagnant_revenu_derniers_jours": 6,
            "nombre_jeunes_avec_travail": 31,
            "existance_enclos_betails": "Non",
            "premier_besoin_prioritaire": "Assistance en cash",
            "deuxieme_besoin_prioritaire": "Eau potable",
            "troisieme_besoin_prioritaire": "Soins de santé",
        },
        "cartographie_acteurs_services": {
            "service_education": "Inadequat",
            "distribution_vivres": "Inadequat",
            "service_sante": "Inadequat",
            "service_sante_mental_psychosocial": "Inadequat",
            "service_moyen_existance": "Inadequat",
            "distribution_cash": "Inadequat",
            "distribution_nfi_ame": "Inadequat",
            "service_protection": "Inadequat",
            "service_maintenace_abris": "Inadequat",
            "service_wash": "Inadequat",
            "service_elimination_dechets": "Inadequat",
            "noms_partenaires_protection": "INTERSOS",
            "noms_partenaires_vbg": "Medecins Sans Frontieres (MSF)",
            "noms_partenaires_protection_enfants": "",
            "noms_partenaires_education": "",
            "noms_partenaires_abris_ame": "",
            "noms_partenaires_sante_eau": "Medecins du Monde France (MdM-F)",
            "noms_partenaires_assainissement": "",
            "noms_partenaires_dechets": "",
            "noms_partenaires_santes_primaires": "",
            "noms_partenaires_sante_secondaires": "",
            "noms_partenaires_sante_mental_psychosociaux": "",
            "noms_partenaires_nutrition": "",
            "noms_partenaires_securite_alimentaire": "",
            "noms_partenaires_cohension_sociale": "",
            "noms_partenaires_moyens_subsistance": "",
            "noms_partenaires_communication": "",
        },
    },
]
