# Generated by Django 5.1.6 on 2025-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
