# Generated by Django 5.1.6 on 2025-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0002_alter_localisation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='type',
            field=models.CharField(choices=[('pays', 'Pays'), ('province', 'Province'), ('territoire', 'Territoire'), ('ville', 'Ville'), ('commune', 'Commune'), ('secteur', 'Secteur'), ('groupement', 'Groupement'), ('quartier', 'Quartier'), ('avenue', 'Avenue'), ('village', 'Village')], default='pays', max_length=30, verbose_name='Type'),
        ),
    ]
