# Generated by Django 5.1.6 on 2025-05-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0003_alter_localisation_code_alter_localisation_nom_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localisation',
            unique_together={('type', 'nom')},
        ),
    ]
