# Generated by Django 5.1.6 on 2025-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0004_alter_localisation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='type',
            field=models.CharField(choices=[('pays', 'Pays'), ('province', 'Province'), ('territoire', 'Territoire'), ('ville', 'Ville'), ('commune', 'Commune'), ('secteur', 'Secteur'), ('groupement', 'Groupement'), ('quartier', 'Quartier'), ('avenue', 'Avenue'), ('village', 'Village'), ('zone', 'Zone de Santé'), ('aire', 'Aire de Santé')], default='pays', max_length=30, verbose_name='Type'),
        ),
    ]
