# Generated by Django 5.1.6 on 2025-05-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_province_country_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonesante',
            name='province',
        ),
        migrations.AddField(
            model_name='zonesante',
            name='territoire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.territoire'),
            preserve_default=False,
        ),
    ]
