# Generated by Django 5.1.6 on 2025-06-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_dataimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='type_mouvement',
            field=models.CharField(default='entree', max_length=300),
        ),
    ]
