# Generated by Django 5.1.6 on 2025-06-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_dataimport_type_mouvement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimport',
            name='type_mouvement',
        ),
    ]
