# Generated by Django 5.1.6 on 2025-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_dataimport_type_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='code_province',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='code_territoire',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='code_zone_sante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='province',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='territoire',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='zone_sante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
