# Generated by Django 5.1.6 on 2025-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_dataimport_code_province_dataimport_code_territoire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dataimport',
            name='type_site',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
