# Generated by Django 5.1.6 on 2025-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_dataimport_longitude_dataimport_type_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
