# Generated by Django 5.1.6 on 2025-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_dataimport_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=300, null=True)),
                ('code_province', models.CharField(blank=True, max_length=300, null=True)),
                ('territoire', models.CharField(blank=True, max_length=300, null=True)),
                ('code_territoire', models.CharField(blank=True, max_length=300, null=True)),
                ('zone_sante', models.CharField(blank=True, max_length=300, null=True)),
                ('code_zone_sante', models.CharField(blank=True, max_length=300, null=True)),
                ('type_site', models.CharField(blank=True, max_length=300, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('code_site', models.CharField(blank=True, max_length=300, null=True)),
                ('nom_site', models.CharField(max_length=300)),
                ('type_mouvement', models.CharField(default='data_import', max_length=300)),
                ('menages', models.PositiveBigIntegerField(default=0)),
                ('individus', models.PositiveBigIntegerField(default=0)),
                ('date_mise_a_jour', models.DateField()),
            ],
        ),
    ]
