# Generated by Django 5.1.6 on 2025-07-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_monthdata_sitedeplace_mouvementdeplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementdeplace',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='mouvementdeplace',
            name='site',
        ),
        migrations.DeleteModel(
            name='MonthData',
        ),
        migrations.DeleteModel(
            name='MouvementDeplace',
        ),
        migrations.DeleteModel(
            name='SiteDeplace',
        ),
    ]
