# Generated by Django 5.1.6 on 2025-07-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_remove_mouvementdeplace_mois_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataImport',
        ),
        migrations.DeleteModel(
            name='TemporalDataImport',
        ),
    ]
